//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 11:11:22 AM CDT 
//


package com.emc.cdp.mgmt.bean;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Account complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Account">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="state" type="{http://cdp.emc.com/services/rest/model}accountState" minOccurs="0"/>
 *         &lt;element name="attribute" type="{http://cdp.emc.com/services/rest/model}Attribute" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="subscription" type="{http://cdp.emc.com/services/rest/model}Subscription" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Account", propOrder = {
    "id",
    "name",
    "type",
    "description",
    "state",
    "attributes",
    "subscriptions"
})
@XmlRootElement(name = "account")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
public class Account {

    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    protected String id;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    protected String name;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    protected String type;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    protected String description;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    protected AccountState state;
    @XmlElement(name = "attribute", nillable = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    protected List<Attribute> attributes;
    @XmlElement(name = "subscription", nillable = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    protected List<Subscription> subscriptions;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link AccountState }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public AccountState getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountState }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public void setState(AccountState value) {
        this.state = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Attribute }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public List<Attribute> getAttributes() {
        if (attributes == null) {
            attributes = new ArrayList<Attribute>();
        }
        return this.attributes;
    }

    /**
     * Gets the value of the subscriptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subscriptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubscriptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Subscription }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public List<Subscription> getSubscriptions() {
        if (subscriptions == null) {
            subscriptions = new ArrayList<Subscription>();
        }
        return this.subscriptions;
    }

}
