//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 11:11:22 AM CDT 
//


package com.emc.cdp.mgmt.bean;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lifecycleEventType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="lifecycleEventType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="user_cancel"/>
 *     &lt;enumeration value="user_restore"/>
 *     &lt;enumeration value="admin_suspend"/>
 *     &lt;enumeration value="admin_cancel"/>
 *     &lt;enumeration value="admin_close"/>
 *     &lt;enumeration value="admin_restore"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "lifecycleEventType")
@XmlEnum
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
public enum LifecycleEventType {

    @XmlEnumValue("user_cancel")
    USER_CANCEL("user_cancel"),
    @XmlEnumValue("user_restore")
    USER_RESTORE("user_restore"),
    @XmlEnumValue("admin_suspend")
    ADMIN_SUSPEND("admin_suspend"),
    @XmlEnumValue("admin_cancel")
    ADMIN_CANCEL("admin_cancel"),
    @XmlEnumValue("admin_close")
    ADMIN_CLOSE("admin_close"),
    @XmlEnumValue("admin_restore")
    ADMIN_RESTORE("admin_restore");
    private final String value;

    LifecycleEventType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LifecycleEventType fromValue(String v) {
        for (LifecycleEventType c: LifecycleEventType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
