//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 11:11:22 AM CDT 
//


package com.emc.cdp.mgmt.bean;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for MeteringUsage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeteringUsage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subscriptionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tokenGroupId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tokenId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="endTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="usage" type="{http://cdp.emc.com/services/rest/model}Usage" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeteringUsage", propOrder = {
    "subscriptionId",
    "tokenGroupId",
    "tokenId",
    "startTime",
    "endTime",
    "usages"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
public class MeteringUsage {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    protected String subscriptionId;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    protected String tokenGroupId;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    protected String tokenId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    protected XMLGregorianCalendar startTime;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    protected XMLGregorianCalendar endTime;
    @XmlElement(name = "usage")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    protected List<Usage> usages;

    /**
     * Gets the value of the subscriptionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public String getSubscriptionId() {
        return subscriptionId;
    }

    /**
     * Sets the value of the subscriptionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public void setSubscriptionId(String value) {
        this.subscriptionId = value;
    }

    /**
     * Gets the value of the tokenGroupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public String getTokenGroupId() {
        return tokenGroupId;
    }

    /**
     * Sets the value of the tokenGroupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public void setTokenGroupId(String value) {
        this.tokenGroupId = value;
    }

    /**
     * Gets the value of the tokenId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public String getTokenId() {
        return tokenId;
    }

    /**
     * Sets the value of the tokenId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public void setTokenId(String value) {
        this.tokenId = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public XMLGregorianCalendar getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public void setEndTime(XMLGregorianCalendar value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the usages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Usage }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
    public List<Usage> getUsages() {
        if (usages == null) {
            usages = new ArrayList<Usage>();
        }
        return this.usages;
    }

}
