//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 11:11:22 AM CDT 
//


package com.emc.cdp.mgmt.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.emc.cdp.mgmt.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.emc.cdp.mgmt.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvitationList }
     * 
     */
    public InvitationList createInvitationList() {
        return new InvitationList();
    }

    /**
     * Create an instance of {@link Invitation }
     * 
     */
    public Invitation createInvitation() {
        return new Invitation();
    }

    /**
     * Create an instance of {@link IdentityList }
     * 
     */
    public IdentityList createIdentityList() {
        return new IdentityList();
    }

    /**
     * Create an instance of {@link Identity }
     * 
     */
    public Identity createIdentity() {
        return new Identity();
    }

    /**
     * Create an instance of {@link AccountRoleList }
     * 
     */
    public AccountRoleList createAccountRoleList() {
        return new AccountRoleList();
    }

    /**
     * Create an instance of {@link AccountRole }
     * 
     */
    public AccountRole createAccountRole() {
        return new AccountRole();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link Attribute }
     * 
     */
    public Attribute createAttribute() {
        return new Attribute();
    }

    /**
     * Create an instance of {@link ApplicationList }
     * 
     */
    public ApplicationList createApplicationList() {
        return new ApplicationList();
    }

    /**
     * Create an instance of {@link Application }
     * 
     */
    public Application createApplication() {
        return new Application();
    }

    /**
     * Create an instance of {@link Subscription }
     * 
     */
    public Subscription createSubscription() {
        return new Subscription();
    }

    /**
     * Create an instance of {@link Subtenant }
     * 
     */
    public Subtenant createSubtenant() {
        return new Subtenant();
    }

    /**
     * Create an instance of {@link Token }
     * 
     */
    public Token createToken() {
        return new Token();
    }

    /**
     * Create an instance of {@link ResourceTagList }
     * 
     */
    public ResourceTagList createResourceTagList() {
        return new ResourceTagList();
    }

    /**
     * Create an instance of {@link ResourceTag }
     * 
     */
    public ResourceTag createResourceTag() {
        return new ResourceTag();
    }

    /**
     * Create an instance of {@link LifecycleEvent }
     * 
     */
    public LifecycleEvent createLifecycleEvent() {
        return new LifecycleEvent();
    }

    /**
     * Create an instance of {@link SubtenantList }
     * 
     */
    public SubtenantList createSubtenantList() {
        return new SubtenantList();
    }

    /**
     * Create an instance of {@link AssigneeList }
     * 
     */
    public AssigneeList createAssigneeList() {
        return new AssigneeList();
    }

    /**
     * Create an instance of {@link Assignee }
     * 
     */
    public Assignee createAssignee() {
        return new Assignee();
    }

    /**
     * Create an instance of {@link AccountList }
     * 
     */
    public AccountList createAccountList() {
        return new AccountList();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

    /**
     * Create an instance of {@link TokenGroupRoleList }
     * 
     */
    public TokenGroupRoleList createTokenGroupRoleList() {
        return new TokenGroupRoleList();
    }

    /**
     * Create an instance of {@link TokenGroupRole }
     * 
     */
    public TokenGroupRole createTokenGroupRole() {
        return new TokenGroupRole();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link Agreement }
     * 
     */
    public Agreement createAgreement() {
        return new Agreement();
    }

    /**
     * Create an instance of {@link TokenGroupList }
     * 
     */
    public TokenGroupList createTokenGroupList() {
        return new TokenGroupList();
    }

    /**
     * Create an instance of {@link TokenGroup }
     * 
     */
    public TokenGroup createTokenGroup() {
        return new TokenGroup();
    }

    /**
     * Create an instance of {@link MeteringUsageList }
     * 
     */
    public MeteringUsageList createMeteringUsageList() {
        return new MeteringUsageList();
    }

    /**
     * Create an instance of {@link MeteringUsage }
     * 
     */
    public MeteringUsage createMeteringUsage() {
        return new MeteringUsage();
    }

    /**
     * Create an instance of {@link SupportIssue }
     * 
     */
    public SupportIssue createSupportIssue() {
        return new SupportIssue();
    }

    /**
     * Create an instance of {@link TokenList }
     * 
     */
    public TokenList createTokenList() {
        return new TokenList();
    }

    /**
     * Create an instance of {@link SubscriptionList }
     * 
     */
    public SubscriptionList createSubscriptionList() {
        return new SubscriptionList();
    }

    /**
     * Create an instance of {@link Usage }
     * 
     */
    public Usage createUsage() {
        return new Usage();
    }

}
