//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 11:11:22 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cdp.emc.com/services/rest/model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.emc.cdp.mgmt.bean;
