//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.23 at 11:11:22 AM CDT 
//


package com.emc.cdp.mgmt.bean;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for subscriptionState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="subscriptionState">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="unprovisioned"/>
 *     &lt;enumeration value="active"/>
 *     &lt;enumeration value="pending_cancellation"/>
 *     &lt;enumeration value="suspended"/>
 *     &lt;enumeration value="cancelled"/>
 *     &lt;enumeration value="closed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "subscriptionState")
@XmlEnum
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2012-05-23T11:11:22-05:00", comments = "JAXB RI v2.2.4")
public enum SubscriptionState {

    @XmlEnumValue("unprovisioned")
    UNPROVISIONED("unprovisioned"),
    @XmlEnumValue("active")
    ACTIVE("active"),
    @XmlEnumValue("pending_cancellation")
    PENDING_CANCELLATION("pending_cancellation"),
    @XmlEnumValue("suspended")
    SUSPENDED("suspended"),
    @XmlEnumValue("cancelled")
    CANCELLED("cancelled"),
    @XmlEnumValue("closed")
    CLOSED("closed");
    private final String value;

    SubscriptionState(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SubscriptionState fromValue(String v) {
        for (SubscriptionState c: SubscriptionState.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
